// Generated by CoffeeScript 1.10.0
var container, imgInd, imgs;

imgs = document.getElementsByTagName("img");

container = document.getElementsByClassName('container-fluid')[0];

imgInd = 0;

window.addEventListener("keydown", function(e) {
  var imgSrc;
  if (e.keyCode === 38 || 40) {
    e.preventDefault();
  }
  if (event.keyCode === 40) {
    if (imgInd < imgs.length - 1) {
      imgInd += 1;
      imgs[imgInd - 1].style.borderColor = "black";
    }
  }
  if (event.keyCode === 38) {
    console.log(imgInd);
    if (imgInd !== 0) {
      imgInd -= 1;
      imgs[imgInd + 1].style.borderColor = "black";
    }
  }
  imgSrc = imgs[imgInd].src.split("static")[1];
  imgs[imgInd].style.borderColor = "darkred";
  container.style.background = "url(static" + imgSrc + ") no-repeat center center fixed";
  return container.style.backgroundSize = "cover";
});
